### ISSUE TITLE
Style reverts on input

### ISSUE THREAD

**Issue by thdoan** [craigbuckler/datalist-css#2]
It's cool you were able to style the initial datalist menu in Country, but I noticed in Chrome as soon as you begin typing it reverts back to the browser style.

**Comment by craigbuckler** [comment]
The demonstration at https://codepen.io/craigbuckler/pen/OJRYaNq still works fine in Chrome. I guess you're either using a conflicting Chrome extension or the webpage you're testing has a problem - possibly that `autocomplete` is not set to `"off"` on the field.
