### ISSUE TITLE
Won't style range input datalist options

### ISSUE THREAD

**Issue by Laiteux** [craigbuckler/datalist-css#4]
Is this intended / not possible at all?

```html
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/datalist-css/dist/datalist-css.min.js"></script>

        <style>
            datalist option {
                background-color: #f00;
            }
        </style>
    </head>
    <body>
        <input type="range" list="discounts" min="1" max="100" value="10">

        <datalist id="discounts">
            <option value="25"></option>
            <option value="50"></option>
            <option value="75"></option>
            <option value="100"></option>
        </datalist>
    </body>
</html>
```

![msedge_Ve6NK4EhpE](https://github.com/craigbuckler/datalist-css/assets/33204743/fca28433-d089-4e40-805a-9645bc80336f)

**Comment by craigbuckler** [comment]
This project is for styling text auto-complete inputs.
Even then, it's an example I don't recommend you use!

You can use a `datalist` for range inputs although some browsers may not support it.

Your example doesn't need it anyway - it'd be better to use `step`:
```html
<input type="range" value="25" min="25" max="100" step="25" />
```

You can then style the range how you want it.
